//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentProfile) DeepCopyInto(out *AssessmentProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentProfile.
func (in *AssessmentProfile) DeepCopy() *AssessmentProfile {
	if in == nil {
		return nil
	}
	out := new(AssessmentProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AssessmentProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentProfileList) DeepCopyInto(out *AssessmentProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AssessmentProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentProfileList.
func (in *AssessmentProfileList) DeepCopy() *AssessmentProfileList {
	if in == nil {
		return nil
	}
	out := new(AssessmentProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AssessmentProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentProfileSpec) DeepCopyInto(out *AssessmentProfileSpec) {
	*out = *in
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = new(ThresholdOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.EnabledValidators != nil {
		in, out := &in.EnabledValidators, &out.EnabledValidators
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisabledValidators != nil {
		in, out := &in.DisabledValidators, &out.DisabledValidators
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisabledChecks != nil {
		in, out := &in.DisabledChecks, &out.DisabledChecks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentProfileSpec.
func (in *AssessmentProfileSpec) DeepCopy() *AssessmentProfileSpec {
	if in == nil {
		return nil
	}
	out := new(AssessmentProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentProfileStatus) DeepCopyInto(out *AssessmentProfileStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentProfileStatus.
func (in *AssessmentProfileStatus) DeepCopy() *AssessmentProfileStatus {
	if in == nil {
		return nil
	}
	out := new(AssessmentProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentSnapshot) DeepCopyInto(out *AssessmentSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentSnapshot.
func (in *AssessmentSnapshot) DeepCopy() *AssessmentSnapshot {
	if in == nil {
		return nil
	}
	out := new(AssessmentSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AssessmentSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentSnapshotList) DeepCopyInto(out *AssessmentSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AssessmentSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentSnapshotList.
func (in *AssessmentSnapshotList) DeepCopy() *AssessmentSnapshotList {
	if in == nil {
		return nil
	}
	out := new(AssessmentSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AssessmentSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentSnapshotSpec) DeepCopyInto(out *AssessmentSnapshotSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentSnapshotSpec.
func (in *AssessmentSnapshotSpec) DeepCopy() *AssessmentSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(AssessmentSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentSnapshotStatus) DeepCopyInto(out *AssessmentSnapshotStatus) {
	*out = *in
	in.RunTime.DeepCopyInto(&out.RunTime)
	in.Summary.DeepCopyInto(&out.Summary)
	out.ClusterInfo = in.ClusterInfo
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]FindingSnapshot, len(*in))
		copy(*out, *in)
	}
	if in.Delta != nil {
		in, out := &in.Delta, &out.Delta
		*out = new(DeltaSummary)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentSnapshotStatus.
func (in *AssessmentSnapshotStatus) DeepCopy() *AssessmentSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(AssessmentSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentSummary) DeepCopyInto(out *AssessmentSummary) {
	*out = *in
	if in.Score != nil {
		in, out := &in.Score, &out.Score
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentSummary.
func (in *AssessmentSummary) DeepCopy() *AssessmentSummary {
	if in == nil {
		return nil
	}
	out := new(AssessmentSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAssessment) DeepCopyInto(out *ClusterAssessment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAssessment.
func (in *ClusterAssessment) DeepCopy() *ClusterAssessment {
	if in == nil {
		return nil
	}
	out := new(ClusterAssessment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterAssessment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAssessmentList) DeepCopyInto(out *ClusterAssessmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterAssessment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAssessmentList.
func (in *ClusterAssessmentList) DeepCopy() *ClusterAssessmentList {
	if in == nil {
		return nil
	}
	out := new(ClusterAssessmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterAssessmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAssessmentSpec) DeepCopyInto(out *ClusterAssessmentSpec) {
	*out = *in
	if in.Validators != nil {
		in, out := &in.Validators, &out.Validators
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ReportStorage.DeepCopyInto(&out.ReportStorage)
	if in.HistoryLimit != nil {
		in, out := &in.HistoryLimit, &out.HistoryLimit
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAssessmentSpec.
func (in *ClusterAssessmentSpec) DeepCopy() *ClusterAssessmentSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterAssessmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAssessmentStatus) DeepCopyInto(out *ClusterAssessmentStatus) {
	*out = *in
	if in.LastRunTime != nil {
		in, out := &in.LastRunTime, &out.LastRunTime
		*out = (*in).DeepCopy()
	}
	if in.NextRunTime != nil {
		in, out := &in.NextRunTime, &out.NextRunTime
		*out = (*in).DeepCopy()
	}
	out.ClusterInfo = in.ClusterInfo
	in.Summary.DeepCopyInto(&out.Summary)
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]Finding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Delta != nil {
		in, out := &in.Delta, &out.Delta
		*out = new(DeltaSummary)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAssessmentStatus.
func (in *ClusterAssessmentStatus) DeepCopy() *ClusterAssessmentStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterAssessmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInfo) DeepCopyInto(out *ClusterInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInfo.
func (in *ClusterInfo) DeepCopy() *ClusterInfo {
	if in == nil {
		return nil
	}
	out := new(ClusterInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapStorageSpec) DeepCopyInto(out *ConfigMapStorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapStorageSpec.
func (in *ConfigMapStorageSpec) DeepCopy() *ConfigMapStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigMapStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeltaSummary) DeepCopyInto(out *DeltaSummary) {
	*out = *in
	if in.NewFindings != nil {
		in, out := &in.NewFindings, &out.NewFindings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResolvedFindings != nil {
		in, out := &in.ResolvedFindings, &out.ResolvedFindings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RegressionFindings != nil {
		in, out := &in.RegressionFindings, &out.RegressionFindings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImprovedFindings != nil {
		in, out := &in.ImprovedFindings, &out.ImprovedFindings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ScoreDelta != nil {
		in, out := &in.ScoreDelta, &out.ScoreDelta
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeltaSummary.
func (in *DeltaSummary) DeepCopy() *DeltaSummary {
	if in == nil {
		return nil
	}
	out := new(DeltaSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Finding) DeepCopyInto(out *Finding) {
	*out = *in
	if in.References != nil {
		in, out := &in.References, &out.References
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Remediation != nil {
		in, out := &in.Remediation, &out.Remediation
		*out = new(RemediationGuidance)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Finding.
func (in *Finding) DeepCopy() *Finding {
	if in == nil {
		return nil
	}
	out := new(Finding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindingSnapshot) DeepCopyInto(out *FindingSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindingSnapshot.
func (in *FindingSnapshot) DeepCopy() *FindingSnapshot {
	if in == nil {
		return nil
	}
	out := new(FindingSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitStorageSpec) DeepCopyInto(out *GitStorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitStorageSpec.
func (in *GitStorageSpec) DeepCopy() *GitStorageSpec {
	if in == nil {
		return nil
	}
	out := new(GitStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationCommand) DeepCopyInto(out *RemediationCommand) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationCommand.
func (in *RemediationCommand) DeepCopy() *RemediationCommand {
	if in == nil {
		return nil
	}
	out := new(RemediationCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationGuidance) DeepCopyInto(out *RemediationGuidance) {
	*out = *in
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]RemediationCommand, len(*in))
		copy(*out, *in)
	}
	if in.Prerequisites != nil {
		in, out := &in.Prerequisites, &out.Prerequisites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationGuidance.
func (in *RemediationGuidance) DeepCopy() *RemediationGuidance {
	if in == nil {
		return nil
	}
	out := new(RemediationGuidance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportStorageSpec) DeepCopyInto(out *ReportStorageSpec) {
	*out = *in
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(ConfigMapStorageSpec)
		**out = **in
	}
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(GitStorageSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportStorageSpec.
func (in *ReportStorageSpec) DeepCopy() *ReportStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ReportStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdOverrides) DeepCopyInto(out *ThresholdOverrides) {
	*out = *in
	if in.MinControlPlaneNodes != nil {
		in, out := &in.MinControlPlaneNodes, &out.MinControlPlaneNodes
		*out = new(int)
		**out = **in
	}
	if in.MinWorkerNodes != nil {
		in, out := &in.MinWorkerNodes, &out.MinWorkerNodes
		*out = new(int)
		**out = **in
	}
	if in.MaxPodsPerNode != nil {
		in, out := &in.MaxPodsPerNode, &out.MaxPodsPerNode
		*out = new(int)
		**out = **in
	}
	if in.MaxClusterAdminBindings != nil {
		in, out := &in.MaxClusterAdminBindings, &out.MaxClusterAdminBindings
		*out = new(int)
		**out = **in
	}
	if in.RequireNetworkPolicy != nil {
		in, out := &in.RequireNetworkPolicy, &out.RequireNetworkPolicy
		*out = new(bool)
		**out = **in
	}
	if in.RequireResourceQuotas != nil {
		in, out := &in.RequireResourceQuotas, &out.RequireResourceQuotas
		*out = new(bool)
		**out = **in
	}
	if in.RequireLimitRanges != nil {
		in, out := &in.RequireLimitRanges, &out.RequireLimitRanges
		*out = new(bool)
		**out = **in
	}
	if in.MaxDaysWithoutUpdate != nil {
		in, out := &in.MaxDaysWithoutUpdate, &out.MaxDaysWithoutUpdate
		*out = new(int)
		**out = **in
	}
	if in.AllowPrivilegedContainers != nil {
		in, out := &in.AllowPrivilegedContainers, &out.AllowPrivilegedContainers
		*out = new(bool)
		**out = **in
	}
	if in.RequireDefaultStorageClass != nil {
		in, out := &in.RequireDefaultStorageClass, &out.RequireDefaultStorageClass
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdOverrides.
func (in *ThresholdOverrides) DeepCopy() *ThresholdOverrides {
	if in == nil {
		return nil
	}
	out := new(ThresholdOverrides)
	in.DeepCopyInto(out)
	return out
}
