apiVersion: v1
kind: Namespace
metadata:
  name: cluster-assessment-operator
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cluster-assessment-operator
  namespace: cluster-assessment-operator
spec: {}
