#!/bin/bash
# update-catalogs.sh - Update FBC catalog templates with a new version
#
# Usage: ./scripts/update-catalogs.sh <new-version>
#
# This script updates all catalog templates (v4.12-v4.20) to include a new bundle version.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CATALOG_TEMPLATES_DIR="$PROJECT_ROOT/catalog-templates"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

usage() {
    echo "Usage: $0 <new-version>"
    echo ""
    echo "Arguments:"
    echo "  new-version        Version to add (e.g., v1.2.11 or 1.2.11)"
    echo ""
    echo "Example:"
    echo "  $0 v1.2.11"
    echo "  $0 1.3.0"
    exit 1
}

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Parse arguments
if [[ $# -lt 1 ]]; then
    usage
fi

NEW_VERSION="$1"
# Remove 'v' prefix if present for consistency
NEW_VERSION="${NEW_VERSION#v}"

# Validate catalog templates directory
if [[ ! -d "$CATALOG_TEMPLATES_DIR" ]]; then
    log_error "Catalog templates directory not found: $CATALOG_TEMPLATES_DIR"
    exit 1
fi

# Registry info
REGISTRY="ghcr.io/diegobskt"
OPERATOR_NAME="cluster-assessment-operator"
BUNDLE_IMAGE="${REGISTRY}/${OPERATOR_NAME}-bundle:v${NEW_VERSION}"

log_info "Updating catalogs for version: v${NEW_VERSION}"
log_info "Bundle image: ${BUNDLE_IMAGE}"

# Process each catalog template
for template in "$CATALOG_TEMPLATES_DIR"/v4.*.yaml; do
    if [[ ! -f "$template" ]]; then
        continue
    fi
    
    ocp_version=$(basename "$template" .yaml)
    log_info "Processing $ocp_version..."
    
    # Generate raw FBC catalog (not a template) with skipRange support.
    # Using raw FBC instead of basic template because:
    # 1. Basic templates don't support skipRange on channel entries
    # 2. OLM requires skipRange in the channel entry (not just CSV) for single-bundle catalogs
    # 3. Without skipRange, OLM can't build upgrade graph from previous versions
    #
    # The skipRange ">=1.0.0 <current" allows upgrades from any 1.x version.
    cat > "$template" << EOF
---
# Raw FBC catalog for cluster-assessment-operator (v${NEW_VERSION})
# Auto-generated by scripts/update-catalogs.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
schema: olm.package
name: cluster-assessment-operator
defaultChannel: stable-v1
---
schema: olm.channel
name: stable-v1
package: cluster-assessment-operator
entries:
  - name: cluster-assessment-operator.v${NEW_VERSION}
    skipRange: ">=1.0.0 <${NEW_VERSION}"
---
schema: olm.channel
name: candidate-v1
package: cluster-assessment-operator
entries:
  - name: cluster-assessment-operator.v${NEW_VERSION}
    skipRange: ">=1.0.0 <${NEW_VERSION}"
---
schema: olm.channel
name: fast-v1
package: cluster-assessment-operator
entries:
  - name: cluster-assessment-operator.v${NEW_VERSION}
    skipRange: ">=1.0.0 <${NEW_VERSION}"
---
schema: olm.bundle
name: cluster-assessment-operator.v${NEW_VERSION}
package: cluster-assessment-operator
image: ${BUNDLE_IMAGE}
properties:
  - type: olm.package
    value:
      packageName: cluster-assessment-operator
      version: ${NEW_VERSION}
EOF
    
    log_info "Updated $template"
done

log_info "All catalog templates updated successfully!"
log_info ""
log_info "Next steps:"
log_info "  1. Regenerate catalogs: make catalogs"
log_info "  2. Validate catalogs:   make catalog-validate"
log_info "  3. Build catalog images: make catalog-build"
log_info "  4. Push catalog images:  make catalog-push"
